### ISSUE TITLE
无法运行

### ISSUE THREAD

**Issue by Meiqi709** [CDWEN0526/tmd-top#1]
![image](https://github.com/user-attachments/assets/ac8ef03a-0e06-4855-9488-aa6b9de04274)
之前用root安装，使用良好，隔了一段时间之后就打不开了。。

**Comment by CDWEN0526** [comment]
该问题是因为无法打开sqlite数据库文件导致的，请确保sqlite数据库文件有足够的权限读写。

**Comment by CDWEN0526** [comment]
将会在下一个版本中使用内存的方式来存储数据，请耐心等待下一个版本

**Comment by Meiqi709** [comment]
感谢大佬！加了权限之后可以运行了！
